### ISSUE TITLE
pixel detection is not working

### ISSUE THREAD

**Issue by vandsonfalcao** [angelbt91/ff-pixel-helper#28]
System:
-   Host: developer-pc Kernel: 5.15.55-1-MANJARO arch: x86_64 bits: 64 
-   Desktop: GNOME v: 42.3.1 Distro: Manjaro Linux
Browser: https://archlinux.org/packages/extra/x86_64/firefox/
![image](https://user-images.githubusercontent.com/65142350/183909844-9f271bf3-7e6f-4a36-9dea-4e620364f687.png)

**Comment by angelbt91** [comment]
Hi @vandsonfalcao! Thanks for opening this issue.

I visited globo.com and I can see a pixel firing on the extension, so it could be something related to your system. Is only on globo.com where you don't see the pixel firing, or is it everywhere?

Also, did you had the chance to review the items that appear when you click on "Why?". I suppose that yes, as you opened this issue, but I ask you just to make sure. Probably it's being caused by another extension that blocks the Facebook pixel or the built-in Firefox's tracking prevention. Could you send me a list of extensions you have installed, and if you have any Firefox built-in tracking prevention enabled?

Thanks!

**Comment by vandsonfalcao** [comment]
oops!

As you said, as shown by the symbol of the shield in blue in the URL bar Firefox's Enhanced Tracking Prevention is enabled.
Thanks for helping me! Sorry for the inconvenience...

**Comment by angelbt91** [comment]
True, the Enhanced Tracking Prevention icon was there all the time haha glad you got this sorted out!

If you have time and you want to do so, submitting a review on [Mozilla's Add-on Store](https://addons.mozilla.org/en-US/firefox/addon/ff-facebook-pixel-helper/) would be much appreciated :) Only if you want, of course!

Thanks again!
